// Generated by CoffeeScript 1.12.7
(function() {
  var getCookie, renderAlert, setCookie;

  getCookie = function(cname) {
    var c, ca, decodedCookie, i, j, name, ref;
    name = cname + "=";
    decodedCookie = decodeURIComponent(document.cookie);
    ca = decodedCookie.split(';');
    for (i = j = 0, ref = ca.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      c = ca[i];
      while (c.charAt(0) === ' ') {
        c = c.substring(1);
      }
      if (c.indexOf(name) === 0) {
        return c.substring(name.length, c.length);
      }
    }
    return false;
  };

  setCookie = function(cname, cvalue, exdays) {
    var d, expires;
    d = new Date();
    d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
    expires = "expires=" + d.toUTCString();
    return document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
  };

  renderAlert = function(message, aclass) {
    if (aclass == null) {
      aclass = 'alert-success';
    }
    $('<div/>', {
      'class': aclass,
      'html': message,
      'id': 'theme-alert'
    }).appendTo('footer');
    return setTimeout(function() {
      return $('#theme-alert').fadeOut(function() {
        return this.remove();
      });
    }, 5000);
  };

  $(function() {
    var analytic, contactForm, popups;
    contactForm = {
      init: function() {
        return $('#contactForm, #footerContactForm').submit(function(e) {
          e.preventDefault();
          return $.post('/wp-admin/admin-ajax.php', $(this).serialize(), function(data) {
            if (data.success) {
              return renderAlert(data.data);
            } else {
              return renderAlert(data.data, 'alert-danger');
            }
          });
        });
      }
    };
    contactForm.init();
    analytic = {
      init: function() {
        analytic.header();
        analytic.footer();
        analytic.single();
        analytic.sidebar();
        analytic.archive();
        analytic.search();
        analytic.nfp();
        analytic.exit();
        return analytic.chat();
      },
      header: function() {
        $('.header_write_my_paper').click(function() {
          return ga('send', 'event', 'CTA', 'menu', 'Write My Paper');
        });
        $('.header_hire_writer').click(function() {
          return ga('send', 'event', 'CTA', 'menu', 'Hire Writer');
        });
        return $('.header_log_in').click(function() {
          return ga('send', 'event', 'CTA', 'click', 'Login');
        });
      },
      footer: function() {
        return $('.footer_banner_fixed').click(function() {
          return ga('send', 'event', 'CTA', 'click', 'footer');
        });
      },
      single: function() {
        return $('.single_banner_middle').click(function() {
          return ga('send', 'event', 'CTA', 'Content page', 'Order Now');
        });
      },
      sidebar: function() {
        return $('.sidebar_banner_widget').click(function() {
          return ga('send', 'event', 'CTA', 'Side Bar', 'Order Now');
        });
      },
      archive: function() {
        return $('.archive_banner_middle').click(function() {
          return ga('send', 'event', 'CTA', 'click', 'category topic');
        });
      },
      search: function() {
        return $('.search_banner_middle').click(function() {
          return ga('send', 'event', 'CTA', 'click', 'search page');
        });
      },
      nfp: function() {
        return $('.nfp_banner_middle').click(function() {
          return ga('send', 'event', 'CTA', 'click', '404 page');
        });
      },
      exit: function() {
        return $('.exit_banner_button').click(function() {
          return ga('send', 'event', 'pop up', 'click', 'exit');
        });
      },
      chat: function() {
        return $('.chat_banner_button').click(function() {
          return ga('send', 'event', 'pop up', 'click', '20sec_CheckItOut');
        });
      }
    };
    analytic.init();
    popups = {
      state: true,
      init: function() {
        popups._data.copy();
        return popups._data.exit();
      },
      show: function(name) {
        if (!popups.state) {
          return false;
        }
        popups.state = false;
        return $.post('/wp-admin/admin-ajax.php', {
          action: 'get_popup_action',
          popup_name: name,
          postID: JSData.postID
        }).done(function(banner) {
          $('#footer').append(banner.data);
          $.magnificPopup.open({
            items: {
              src: '#phdessay-' + name,
              type: 'inline'
            },
            callbacks: {
              close: function() {
                popups.state = true;
                $('#phdessay-' + name).remove();
                return ga('send', 'event', 'pop up', 'close', name);
              }
            }
          });
          return ga('send', 'event', 'pop up', 'appear', name);
        });
      },
      _data: {
        copy: function() {
          return $(document).bind('copy cut', function(e) {
            if (JSData.isSingle) {
              e.preventDefault();
              return popups.show('copy');
            }
          });
        },
        exit: function() {
          function getCookieNew(name) {
            var matches = document.cookie.match(new RegExp("(?:^|; )" + name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, '\\$1') + "=([^;]*)"));
            return matches ? decodeURIComponent(matches[1]) : undefined;
          }

          $(document).mouseleave(function(e){
            if (e.pageY - $(window).scrollTop() <= 1) {
              var alertwin = getCookieNew("alertwin");
              
              if (alertwin != "no") {
                popups.show('exit');

                var date = new Date;
                date.setDate(date.getDate() + 1);
                document.cookie = "alertwin=no; path=/; expires=" + date.toUTCString();
              }
            }
          });

          // var lastYpos;
          // if (getCookie('exit_popup') !== 1 && $(window).width() > 768) {
          //   lastYpos = 0;
          //   return $(window).on('mousemove', function(e) {
          //     if (lastYpos > e.clientY && lastYpos < 5 && !getCookie('exit_popup') && popups.state) {
          //       popups.show('exit');
          //       setCookie('exit_popup', 1, 1);
          //     }
          //     return lastYpos = e.clientY;
          //   });
          // }
        }
      }
    };
    popups.init();
    return $(document).on('submit', '#nocopy_form', function() {
      $.post('/wp-admin/admin-ajax.php', $(this).serialize() + '&postID=' + JSData.postID).done(function(json) {
        if (json.success) {
          renderAlert(json.data);
          popups.state = true;
          return $.magnificPopup.close();
        } else {
          return renderAlert(json.data, 'alert-danger');
        }
      });
      return false;
    });
  });

}).call(this);



//# sourceMappingURL=main.js.map


$(function() {
  // $('.has-dropdown a').on('click', function(e) {
  //   e.preventDefault();
  // })
})

// function clippedText() {
//   let title = $('.phdessay__single-blog h1');
//   let titleMd = $('.phdessay__single-blog-content h2');
//   let titleSm = $('.phdessay__single-blog-content h3');
//   let titleXs = $('.phdessay__single-blog-content h4');
//   let text = $('.phdessay__single-blog-content > p');
//   let listOl = $('.phdessay__single-blog-content ol');
//   let listUl = $('.phdessay__single-blog-content > ul');

//   let counter = 0;
//   let limit = 100;

//   title.addClass('js-content');

//   titleMd.each(function() {
//     $(this).addClass('js-content');
//   })

//   titleSm.each(function() {
//     $(this).addClass('js-content');
//   })

//   titleXs.each(function() {
//     $(this).addClass('js-content');
//   })

//   text.each(function() {
//     $(this).addClass('js-content');
//   })

//   listOl.each(function() {
//     $(this).addClass('js-content');
//   })

//   listUl.each(function() {
//     $(this).addClass('js-content');
//   })

//   let sliceText = $('.js-content');

//   $(sliceText).each(function(i, el){
//     if(counter < limit) {
//       counter += $(this).text().split(' ').length;
//     }else {
//       $(this).addClass('is-blurred');
//     }
//   })
// }

// clippedText();

// function getCookies(name) {
//  var matches = document.cookie.match(new RegExp("(?:^|; )" + name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, '\\$1') + "=([^;]*)"));
//  return matches ? decodeURIComponent(matches[1]) : undefined;
// }

var cookie1 = getCookie('showBlurText');


var cookiepageurl = JSON.parse(getCookie('pageUrl'));

cookiepageurl.map(function(item){
    if (item == window.location.href ) {
       
        $('.phdessay__article-full').addClass('showContent');
        $('.is-blurred').addClass('showContent');
        $('.phdessay__article-share-tosee').hide();
    } else {
       
    }
});


// Add Links to mobile screen

window.addEventListener('load', function () {
    var menus = document.querySelector('.phdessay-assets'),
        ul = document.querySelector('.header .menu'),
        arr = menus.children,
        someArr = [],
        newRes = [];
    var copyLinks = Object.assign(someArr, arr);

    if( window.screen.width <= 2560 ){

        for( var i = 0 in copyLinks){
            if( i < 3){
                var li = document.createElement('li'),
                    attr = copyLinks[i].childNodes[0].attributes[1].nodeValue,
                    a = document.createElement('a');
                a.innerText = copyLinks[i].innerText;
                a.setAttribute('href', attr );
                li.appendChild(a);
                newRes.push(li);
            }
            i++;
        }

        for( var u = 0; u < newRes.length; u++){
            newRes[u].className = 'linkHidden';
            ul.appendChild(newRes[u]);
        }
    }
});